name: Main Test Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Additional steps
  cd:
    name: Providers Test
    uses: ./.github/workflows/providers_test.yml
