name: Sub CD

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Additional steps
  cd:
    name: Providers Test
    uses: ./.github/workflows/providers_test.yml
    secrets: inherit
    with:
      providers-directory: "src/providers/"
      stage-url: "https://stage.example.com"

  another-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Additional steps
